# Generated by Django 5.0.2 on 2024-03-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.TextField(default='high'),
            preserve_default=False,
        ),
    ]
