name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python 3.13.1
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.1

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        cd helpdesk
        pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run Tests
      run: |
        cd helpdesk
        pytest

    # Step 5: Deploy to Render
    - name: Deploy to Render
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        clear_cache: true
        wait_deploy: true